// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RipperAcskt/innotaxi/internal/service (interfaces: AuthRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/RipperAcskt/innotaxi/internal/service"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthRepo is a mock of AuthRepo interface.
type MockAuthRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepoMockRecorder
}

// MockAuthRepoMockRecorder is the mock recorder for MockAuthRepo.
type MockAuthRepoMockRecorder struct {
	mock *MockAuthRepo
}

// NewMockAuthRepo creates a new mock instance.
func NewMockAuthRepo(ctrl *gomock.Controller) *MockAuthRepo {
	mock := &MockAuthRepo{ctrl: ctrl}
	mock.recorder = &MockAuthRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepo) EXPECT() *MockAuthRepoMockRecorder {
	return m.recorder
}

// CheckUserByPhoneNumber mocks base method.
func (m *MockAuthRepo) CheckUserByPhoneNumber(arg0 context.Context, arg1 string) (*service.UserSingIn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserByPhoneNumber", arg0, arg1)
	ret0, _ := ret[0].(*service.UserSingIn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserByPhoneNumber indicates an expected call of CheckUserByPhoneNumber.
func (mr *MockAuthRepoMockRecorder) CheckUserByPhoneNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserByPhoneNumber", reflect.TypeOf((*MockAuthRepo)(nil).CheckUserByPhoneNumber), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockAuthRepo) CreateUser(arg0 context.Context, arg1 service.UserSingUp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthRepoMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthRepo)(nil).CreateUser), arg0, arg1)
}
